name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v1
        with:
          github_token: ${{ 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 }}
          branch: gh-pages
          folder: docs/html
