on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
        with:
          github_token: ${{ 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 }}
          branch: gh-pages
          folder: docs/html
          config_file: Doxyfile
